[tool.poetry]
name = "f5-tts"
version = "0.1.1"
description = "F5-TTS: A Fairytaler that Fakes Fluent and Faithful Speech with Flow Matching"
readme = "README.md"
license = "MIT"
authors = ["SWivid <swivid@outlook.com>"]
homepage = "https://github.com/SWivid/F5-TTS"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "1.35.39"
botocore = "1.35.39"
accelerate = ">=0.33.0"
cached_path = "*"
click = "*"
datasets = "*"
ema_pytorch = ">=0.5.2"
gradio = ">=3.45.2"
jieba = "*"
librosa = "*"
matplotlib = "*"
numpy = "<=1.26.4"
pydub = "*"
pypinyin = "*"
safetensors = "*"
soundfile = "*"
tomli = "*"
torch = ">=2.0.0"
torchaudio = ">=2.0.0"
torchdiffeq = "*"
tqdm = ">=4.65.0"
transformers = "*"
transformers_stream_generator = "*"
vocos = "*"
wandb = "*"
x_transformers = ">=1.31.14"
python-dotenv = "^1.0.1"


[tool.poetry.scripts]
f5-tts_infer-cli = "f5_tts.infer.infer_cli:main"
f5-tts_infer-gradio = "f5_tts.infer.infer_gradio:main"
f5-tts_finetune-cli = "f5_tts.train.finetune_cli:main"
f5-tts_finetune-gradio = "f5_tts.train.finetune_gradio:main"
